// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANulOJZsZ1U7JJ6mMbQavwJOgNVovGwho',
    appId: '1:219925601241:web:678729c3b0638a3fe597c8',
    messagingSenderId: '219925601241',
    projectId: 'masarpro',
    authDomain: 'masarpro.firebaseapp.com',
    storageBucket: 'masarpro.firebasestorage.app',
    measurementId: 'G-0QTJ4QMQ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxO1q0TKRWGP-RyazJcqQL2DVCtVQY_M',
    appId: '1:219925601241:android:84997dba09066161e597c8',
    messagingSenderId: '219925601241',
    projectId: 'masarpro',
    storageBucket: 'masarpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pMjI8UvsBVt6qsYCzivbSZIl2oyoCd8',
    appId: '1:219925601241:ios:2b5119c210b8f9a9e597c8',
    messagingSenderId: '219925601241',
    projectId: 'masarpro',
    storageBucket: 'masarpro.firebasestorage.app',
    iosBundleId: 'com.example.masarPro',
  );
}
